### ISSUE TITLE
Test suite fails in IE7

### ISSUE THREAD

**Issue by codysoyland** [mitsuhiko/classy#1]
I didn't try in other IE versions, but some of the QUnit tests do not pass in IE7.

**Comment by finscn** [comment]
change line 105 : 
var rv = function Class() {   

to

var rv = function () {

# 

reason:

line 127-128 :
    rv.$extend = Class.$extend;
    rv.$withData = Class.$withData;

the Class  should be  the 'Class' defined in line 48.
if  rv=function Class()...   the Class will be rv.

**Comment by mitsuhiko** [comment]
Fixed for good. Use 1.3 :)
